### ISSUE TITLE
combine function for property

### ISSUE THREAD

**Issue by PalmZE** [raveclassic/frp-ts#10]
@raveclassic, hi!

Looks like typescript is finally ready to express combine function using tuple types:
```typescript
type PropertyValue<A> = A extends Property<infer U> ? U : never;
type MapPropsToValues<PS extends [Property<unknown>, ...Property<unknown>[]]> = {
  [K in keyof PS]: PropertyValue<PS[K]>;
};

function combine<PS extends [Property<unknown>, ...Property<unknown>[]], B>(
  ...args: [...PS, (...values: MapPropsToValues<PS>) => B]
): Property<B>;
```

Correctly inferred types:
```typescript
const p1 = constProperty(1);
const p2 = constProperty('');
const p3 = constProperty(true);
const p4 = constProperty(new Date());
const pr = combine(p1, p2, p3, p4, (v1, v2, v3, v4) => {
  return { name: 'Bar' };
});
```
![image](https://user-images.githubusercontent.com/16352166/126867101-794d51be-01ae-495f-8ef2-0e04a1620342.png)

Would you accept a PR that adds `combine` to `property` API?

**Comment by raveclassic** [comment]
@PalmZE Sure, feel free to do that 🎉

**Comment by PalmZE** [comment]
@raveclassic sorry for the delay. Would it make sense to do it now?

**Comment by raveclassic** [comment]
@PalmZE not sure, only if you still use it

**Comment by PalmZE** [comment]
Honestly, I'd rather use `1.x.x` version the next time, closing this one.
