### ISSUE TITLE
[Question] Is it really beneficial to have implicit filtering logic on value set?

### ISSUE THREAD

**Issue by Nedgeva** [raveclassic/frp-ts#29]
Hi @raveclassic !
I see that atoms has built-in deduping logic for referentially equal values:
https://github.com/raveclassic/frp-ts/blob/af803aac26064cb54f86bba20ec4bafdacee6cb6/packages/core/src/atom.ts#L20-L25
while i do understand what this made for and most of the time it's very convenient to skip updates for same values, but there are cases where this behavior might be really unwanted.
As for example one can use atoms for some event's payload processing where every single value counts despite the fact they can be identical.

Perhaps it's worth to move out filtering logic to dedicated property operator?

**Comment by Fyzu** [comment]
I discussed about this with @raveclassic.
`frp-ts` not about events, about working with state.
If you need stream and every event is important, use something else. :)

**Comment by Fyzu** [comment]
@raveclassic I think we should warn about this behavior in the documentation. What do you think?

**Comment by raveclassic** [comment]
Hey @Nedgeva, thanks for the issue.
The main idea, as mentioned by @Fyzu, is that `Property`/`Atom` describe values, not sequences of events. There's no "timeline" concept for a `Property`/`Atom`, only its value and _change_ notification. 
Speaking about events, it's semantically incorrect to describe an "event" with a `Property`/`Atom`. We can only describe something like `declare const lastClick: Property<MouseEvent>`. If we want to describe sequence of clicks, we should rather use a push-observable implementation like `rxjs`/`most`.

@Fyzu Good point. Documentation definitely needs improvements. I'll log a linked ticked and close this `[Question]`.
